import streamlit as st
import sqlite3

def show_education(user_id):
    st.markdown('<div class="main-header">Education Center</div>', unsafe_allow_html=True)
    
    # Sidebar for education navigation
    education_category = st.sidebar.radio(
        "Education Categories",
        ["Getting Started", "Technical Analysis", "Fundamental Analysis", "Portfolio Management", "Risk Management", "Glossary"]
    )
    
    if education_category == "Getting Started":
        show_getting_started()
    elif education_category == "Technical Analysis":
        show_technical_analysis()
    elif education_category == "Fundamental Analysis":
        show_fundamental_analysis()
    elif education_category == "Portfolio Management":
        show_portfolio_management()
    elif education_category == "Risk Management":
        show_risk_management()
    elif education_category == "Glossary":
        show_glossary()

def show_getting_started():
    st.markdown('<div class="sub-header">Getting Started with Investing</div>', unsafe_allow_html=True)
    
    # Introduction
    st.markdown("""
    <div class="card">
        <h3>Welcome to Investing</h3>
        <p>
            Investing in the stock market can be an excellent way to build wealth over time. This guide will help you understand the basics of investing and how to get started.
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    # Key concepts
    st.markdown('<div class="sub-header">Key Concepts</div>', unsafe_allow_html=True)
    
    concepts = [
        {
            "title": "What is a Stock?",
            "content": "A stock represents ownership in a company. When you buy a share of stock, you're buying a small piece of that company."
        },
        {
            "title": "Stock Exchanges",
            "content": "Stock exchanges are markets where stocks are bought and sold. The major U.S. exchanges include the New York Stock Exchange (NYSE) and NASDAQ."
        },
        {
            "title": "Bull vs. Bear Markets",
            "content": "A bull market is when stock prices are rising, while a bear market is when stock prices are falling."
        },
        {
            "title": "Diversification",
            "content": "Diversification means spreading your investments across different assets to reduce risk."
        }
    ]
    
    cols = st.columns(2)
    
    for i, concept in enumerate(concepts):
        col = cols[i % 2]
        
        with col:
            st.markdown(f"""
            <div class="card">
                <h3>{concept['title']}</h3>
                <p>{concept['content']}</p>
            </div>
            """, unsafe_allow_html=True)
    
    # Steps to start investing
    st.markdown('<div class="sub-header">Steps to Start Investing</div>', unsafe_allow_html=True)
    
    steps = [
        "Set clear financial goals",
        "Create a budget and determine how much you can invest",
        "Build an emergency fund before investing",
        "Understand your risk tolerance",
        "Research different investment options",
        "Open a brokerage account",
        "Start with a diversified portfolio",
        "Regularly review and adjust your investments"
    ]
    
    for i, step in enumerate(steps):
        st.markdown(f"""
        <div class="step-card">
            <div class="step-number">{i+1}</div>
            <div class="step-content">{step}</div>
        </div>
        """, unsafe_allow_html=True)
    
    # Video tutorial (placeholder)
    st.markdown('<div class="sub-header">Video Tutorial</div>', unsafe_allow_html=True)
    
    st.markdown("""
    <div class="card">
        <h3>Introduction to Investing</h3>
        <div class="video-container">
            <iframe width="100%" height="315" src="https://www.youtube.com/embed/f5j9v9dfinQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
    """, unsafe_allow_html=True)

def show_technical_analysis():
    st.markdown('<div class="sub-header">Technical Analysis</div>', unsafe_allow_html=True)
    
    # Introduction
    st.markdown("""
    <div class="card">
        <h3>Understanding Technical Analysis</h3>
        <p>
            Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity, such as past prices and volume. Technical analysts do not attempt to measure a security's intrinsic value, but instead use charts and other tools to identify patterns that can suggest future activity.
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    # Key indicators
    st.markdown('<div class="sub-header">Key Technical Indicators</div>', unsafe_allow_html=True)
    
    indicators = [
        {
            "title": "Moving Averages",
            "content": "Moving averages smooth out price data to create a single flowing line, making it easier to identify the direction of the trend. Common periods are 50-day and 200-day moving averages."
        },
        {
            "title": "Relative Strength Index (RSI)",
            "content": "RSI measures the speed and change of price movements on a scale from 0 to 100. An asset is considered overbought when RSI is above 70 and oversold when RSI is below 30."
        },
        {
            "title": "MACD (Moving Average Convergence Divergence)",
            "content": "MACD is a trend-following momentum indicator that shows the relationship between two moving averages of a security's price. A bullish signal occurs when the MACD crosses above its signal line, and a bearish signal when it crosses below."
        },
        {
            "title": "Bollinger Bands",
            "content": "Bollinger Bands consist of a middle band (usually a 20-day simple moving average) and two outer bands that are standard deviations away from the middle band. They help identify overbought or oversold conditions."
        }
    ]
    
    for indicator in indicators:
        st.markdown(f"""
        <div class="card">
            <h3>{indicator['title']}</h3>
            <p>{indicator['content']}</p>
        </div>
        """, unsafe_allow_html=True)
    
    # Chart patterns
    st.markdown('<div class="sub-header">Common Chart Patterns</div>', unsafe_allow_html=True)
    
    patterns = [
        {
            "title": "Head and Shoulders",
            "content": "A bearish reversal pattern with three peaks, where the middle peak (head) is higher than the two surrounding peaks (shoulders)."
        },
        {
            "title": "Double Top/Bottom",
            "content": "A double top is a bearish reversal pattern with two peaks at approximately the same level. A double bottom is a bullish reversal pattern with two troughs at approximately the same level."
        },
        {
            "title": "Cup and Handle",
            "content": "A bullish continuation pattern that resembles a cup with a handle, where the cup is a rounded bottom and the handle is a slight downward drift."
        },
        {
            "title": "Flags and Pennants",
            "content": "Short-term continuation patterns that occur after a strong price movement, followed by a consolidation period, before continuing in the same direction."
        }
    ]
    
    cols = st.columns(2)
    
    for i, pattern in enumerate(patterns):
        col = cols[i % 2]
        
        with col:
            st.markdown(f"""
            <div class="card">
                <h3>{pattern['title']}</h3>
                <p>{pattern['content']}</p>
            </div>
            """, unsafe_allow_html=True)

def show_fundamental_analysis():
    st.markdown('<div class="sub-header">Fundamental Analysis</div>', unsafe_allow_html=True)
    
    # Introduction
    st.markdown("""
    <div class="card">
        <h3>Understanding Fundamental Analysis</h3>
        <p>
            Fundamental analysis is a method of evaluating a security in an attempt to measure its intrinsic value, by examining related economic, financial, and other qualitative and quantitative factors. Fundamental analysts study everything that can affect the security's value, including macroeconomic factors and company-specific factors.
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    # Key metrics
    st.markdown('<div class="sub-header">Key Financial Metrics</div>', unsafe_allow_html=True)
    
    metrics = [
        {
            "title": "Earnings Per Share (EPS)",
            "content": "EPS represents the portion of a company's profit allocated to each outstanding share of common stock. It is a key indicator of a company's profitability."
        },
        {
            "title": "Price-to-Earnings Ratio (P/E)",
            "content": "The P/E ratio is the ratio of a company's share price to its earnings per share. A high P/E could mean that a stock's price is high relative to earnings and possibly overvalued, or that investors are expecting high growth rates in the future."
        },
        {
            "title": "Price-to-Book Ratio (P/B)",
            "content": "The P/B ratio compares a company's market value to its book value. A lower P/B ratio could indicate that the stock is undervalued."
        },
        {
            "title": "Debt-to-Equity Ratio",
            "content": "This ratio indicates the relative proportion of shareholders' equity and debt used to finance a company's assets. A high ratio suggests that a company has been aggressive in financing its growth with debt."
        }
    ]
    
    cols = st.columns(2)
    
    for i, metric in enumerate(metrics):
        col = cols[i % 2]
        
        with col:
            st.markdown(f"""
            <div class="card">
                <h3>{metric['title']}</h3>
                <p>{metric['content']}</p>
            </div>
            """, unsafe_allow_html=True)
    
    # Financial statements
    st.markdown('<div class="sub-header">Understanding Financial Statements</div>', unsafe_allow_html=True)
    
    statements = [
        {
            "title": "Income Statement",
            "content": "The income statement shows a company's revenues, expenses, and profits over a specific period. It provides information about a company's ability to generate profit by increasing revenue, reducing costs, or both."
        },
        {
            "title": "Balance Sheet",
            "content": "The balance sheet provides a snapshot of a company's assets, liabilities, and shareholders' equity at a specific point in time. It shows what a company owns and owes, as well as the amount invested by shareholders."
        },
        {
            "title": "Cash Flow Statement",
            "content": "The cash flow statement shows how changes in balance sheet accounts and income affect cash and cash equivalents. It breaks down the analysis into operating, investing, and financing activities."
        }
    ]
    
    for statement in statements:
        st.markdown(f"""
        <div class="card">
            <h3>{statement['title']}</h3>
            <p>{statement['content']}</p>
        </div>
        """, unsafe_allow_html=True)

def show_portfolio_management():
    st.markdown('<div class="sub-header">Portfolio Management</div>', unsafe_allow_html=True)
    
    # Introduction
    st.markdown("""
    <div class="card">
        <h3>Effective Portfolio Management</h3>
        <p>
            Portfolio management is the art and science of making decisions about investment mix and policy, matching investments to objectives, asset allocation for individuals and institutions, and balancing risk against performance.
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    # Key concepts
    st.markdown('<div class="sub-header">Key Concepts</div>', unsafe_allow_html=True)
    
    concepts = [
        {
            "title": "Asset Allocation",
            "content": "Asset allocation is the process of dividing your investments among different asset classes, such as stocks, bonds, and cash. The goal is to balance risk and reward according to your goals, risk tolerance, and investment timeline."
        },
        {
            "title": "Diversification",
            "content": "Diversification involves spreading your investments across various asset classes, sectors, and geographic regions to reduce risk. The idea is that a portfolio of different kinds of investments will, on average, yield higher returns and pose a lower risk than any individual investment."
        },
        {
            "title": "Rebalancing",
            "content": "Rebalancing is the process of realigning the weightings of a portfolio of assets. It involves periodically buying or selling assets in a portfolio to maintain an original or desired level of asset allocation or risk."
        },
        {
            "title": "Dollar-Cost Averaging",
            "content": "Dollar-cost averaging is the practice of investing a fixed amount of money in the same fund or stock at regular intervals over a long period, regardless of the investment's price. This strategy can help reduce the impact of volatility on the overall purchase."
        }
    ]
    
    for concept in concepts:
        st.markdown(f"""
        <div class="card">
            <h3>{concept['title']}</h3>
            <p>{concept['content']}</p>
        </div>
        """, unsafe_allow_html=True)
    
    # Portfolio strategies
    st.markdown('<div class="sub-header">Common Portfolio Strategies</div>', unsafe_allow_html=True)
    
    strategies = [
        {
            "title": "Growth Investing",
            "content": "Growth investing focuses on companies that are expected to grow at an above-average rate compared to other companies. Growth investors typically look for companies with strong earnings growth or revenue growth."
        },
        {
            "title": "Value Investing",
            "content": "Value investing involves picking stocks that appear to be trading for less than their intrinsic or book value. Value investors actively seek stocks they believe the market has undervalued."
        },
        {
            "title": "Income Investing",
            "content": "Income investing focuses on investments that generate a steady income stream, such as dividend-paying stocks, bonds, and real estate investment trusts (REITs)."
        },
        {
            "title": "Index Investing",
            "content": "Index investing involves building a portfolio that tracks a market index, such as the S&P 500. This passive strategy aims to match the performance of the market rather than beat it."
        }
    ]
    
    cols = st.columns(2)
    
    for i, strategy in enumerate(strategies):
        col = cols[i % 2]
        
        with col:
            st.markdown(f"""
            <div class="card">
                <h3>{strategy['title']}</h3>
                <p>{strategy['content']}</p>
            </div>
            """, unsafe_allow_html=True)

def show_risk_management():
    st.markdown('<div class="sub-header">Risk Management</div>', unsafe_allow_html=True)
    
    # Introduction
    st.markdown("""
    <div class="card">
        <h3>Understanding Investment Risk</h3>
        <p>
            Risk management in investing is the process of identifying, analyzing, and accepting or mitigating uncertainty in investment decisions. Effective risk management helps investors minimize potential losses while maximizing returns.
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    # Types of risk
    st.markdown('<div class="sub-header">Types of Investment Risk</div>', unsafe_allow_html=True)
    
    risks = [
        {
            "title": "Market Risk",
            "content": "Market risk is the possibility of an investor experiencing losses due to factors that affect the overall performance of the financial markets. This includes events like economic recessions, political turmoil, or changes in interest rates."
        },
        {
            "title": "Credit Risk",
            "content": "Credit risk is the risk of loss resulting from a borrower's failure to repay a loan or meet contractual obligations. This is particularly relevant for bond investors."
        },
        {
            "title": "Inflation Risk",
            "content": "Inflation risk is the chance that the cash flows from an investment won't be worth as much in the future because of changes in purchasing power due to inflation."
        },
        {
            "title": "Liquidity Risk",
            "content": "Liquidity risk refers to the possibility of not being able to buy or sell investments quickly enough to prevent or minimize a loss. It's often associated with investments that are not easily convertible to cash."
        },
        {
            "title": "Concentration Risk",
            "content": "Concentration risk refers to the risk of amplified losses that may occur from having a large portion of your investments in a particular asset, asset class, or market segment relative to your overall portfolio."
        }
    ]
    
    for risk in risks:
        st.markdown(f"""
        <div class="card">
            <h3>{risk['title']}</h3>
            <p>{risk['content']}</p>
        </div>
        """, unsafe_allow_html=True)
    
    # Risk management strategies
    st.markdown('<div class="sub-header">Risk Management Strategies</div>', unsafe_allow_html=True)
    
    strategies = [
        {
            "title": "Diversification",
            "content": "Diversification involves spreading your investments across various asset classes, sectors, and geographic regions to reduce risk. The idea is that a portfolio of different kinds of investments will, on average, yield higher returns and pose a lower risk than any individual investment."
        },
        {
            "title": "Asset Allocation",
            "content": "Asset allocation is the process of dividing your investments among different asset classes, such as stocks, bonds, and cash. The goal is to balance risk and reward according to your goals, risk tolerance, and investment timeline."
        },
        {
            "title": "Position Sizing",
            "content": "Position sizing refers to the size of a position within a portfolio, or the amount of money invested in a particular security relative to the total portfolio. Proper position sizing can help limit losses and manage risk."
        },
        {
            "title": "Stop-Loss Orders",
            "content": "A stop-loss order is a type of order placed with a broker to buy or sell a security when it reaches a certain price. It's designed to limit an investor's loss on a position in a security."
        }
    ]
    
    cols = st.columns(2)
    
    for i, strategy in enumerate(strategies):
        col = cols[i % 2]
        
        with col:
            st.markdown(f"""
            <div class="card">
                <h3>{strategy['title']}</h3>
                <p>{strategy['content']}</p>
            </div>
            """, unsafe_allow_html=True)

def show_glossary():
    st.markdown('<div class="sub-header">Investment Glossary</div>', unsafe_allow_html=True)
    
    # Introduction
    st.markdown("""
    <div class="card">
        <h3>Understanding Investment Terminology</h3>
        <p>
            This glossary provides definitions for common investment terms to help you better understand the language of investing.
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    # Search functionality
    search_term = st.text_input("Search for a term", "")
    
    # Glossary terms
    terms = [
        {
            "term": "Bear Market",
            "definition": "A market condition in which the prices of securities are falling, and widespread pessimism causes the negative sentiment to be self-sustaining. Generally, a bear market occurs when a broad market index falls by 20% or more over at least a two-month period."
        },
        {
            "term": "Bull Market",
            "definition": "A market condition in which the prices of securities are rising or are expected to rise. The term is most often used to refer to the stock market but can be applied to anything that is traded, such as bonds, currencies, and commodities."
        },
        {
            "term": "Dividend",
            "definition": "A dividend is a distribution of a portion of a company's earnings, decided by the board of directors, to a class of its shareholders. Dividends can be issued as cash payments, as shares of stock, or other property."
        },
        {
            "term": "ETF (Exchange-Traded Fund)",
            "definition": "An ETF is a type of investment fund and exchange-traded product, i.e., they are traded on stock exchanges. ETFs are similar in many ways to mutual funds, except that ETFs are bought and sold throughout the day on stock exchanges."
        },
        {
            "term": "Fundamental Analysis",
            "definition": "Fundamental analysis is a method of evaluating a security in an attempt to measure its intrinsic value, by examining related economic, financial, and other qualitative and quantitative factors."
        },
        {
            "term": "Market Capitalization",
            "definition": "Market capitalization refers to the total dollar market value of a company's outstanding shares. Commonly referred to as 'market cap,' it is calculated by multiplying a company's shares outstanding by the current market price of one share."
        },
        {
            "term": "Mutual Fund",
            "definition": "A mutual fund is an investment vehicle made up of a pool of funds collected from many investors for the purpose of investing in securities such as stocks, bonds, money market instruments, and similar assets."
        },
        {
            "term": "Portfolio",
            "definition": "A portfolio is a collection of financial investments like stocks, bonds, commodities, cash, and cash equivalents, including closed-end funds and exchange-traded funds (ETFs)."
        },
        {
            "term": "Technical Analysis",
            "definition": "Technical analysis is a trading discipline employed to evaluate investments and identify trading opportunities by analyzing statistical trends gathered from trading activity, such as price movement and volume."
        },
        {
            "term": "Volatility",
            "definition": "Volatility is a statistical measure of the dispersion of returns for a given security or market index. In most cases, the higher the volatility, the riskier the security."
        },
        {
            "term": "Yield",
            "definition": "Yield is the income returned on an investment, such as the interest received from holding a security. The yield is usually expressed as an annual percentage rate based on the investment's cost, current market value, or face value."
        }
    ]
    
    # Filter terms based on search
    if search_term:
        filtered_terms = [term for term in terms if search_term.lower() in term['term'].lower() or search_term.lower() in term['definition'].lower()]
    else:
        filtered_terms = terms
    
    # Display terms
    for term in filtered_terms:
        st.markdown(f"""
        <div class="glossary-card">
            <h3>{term['term']}</h3>
            <p>{term['definition']}</p>
        </div>
        """, unsafe_allow_html=True)
